### ISSUE TITLE
How to unwrap result

### ISSUE THREAD

**Issue by JayChandler** [NeovaHealth/t4xmlrpc#1]
So in the documentation there is no example how to unwrap results in a beautiful way. I have a response something like this. How can one for example access the property **DOMAIN** in an easy and elegant way ?

``` scala
List(  Map( PROPERTY -> Map( LIMIT -> List(1000), DOMAIN -> List(ae-immobilien.com))))
```

**Comment by MaxWorgan** [comment]
There isn't a very good way to unwrap results - I never got the chance to add a Zipper or incorporate Lenses. If you fancy giving it a go, I'd happily accept a PR :) In the mean time you could do something like this:

``` scala
for {
 a  <- response.array
 h  <- a.headOption
 m1 <- h.struct
 p  <- m.get("property")
 m2 <- p.struct
 d  <- m2.get("domain")
 f  <- d.array
 r  <- f.headOption
} yield r
```
