### ISSUE TITLE
XmlRpcClient.request causes thread not to exit

### ISSUE THREAD

**Issue by JayChandler** [NeovaHealth/t4xmlrpc#2]
I have a question. Everytime i do a **XmlRpcClient.request** call the main thread of the app does not terminate even all code was executed. It keeps hanging! Why ?

I am using SCALA IDE to launch my app. When i run it via sbt all is fine!

**Comment by MaxWorgan** [comment]
I haven't seen this issue and don't use Scala IDE. However I'll look into this and see if I can replicate. Could you provide some sample code that displays this behaviour?

**Comment by JayChandler** [comment]
It has to do with the underlying dispatch library http://dispatch-classic.databinder.net/Choose+an+Executor.html. It seems u have to call this to get the thread terminated!

```
Http.shutdown()
```
